document.write('	        <div class="container">														')
document.write('	            <div class="navbar-header">														')
document.write('	                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-ul" aria-expanded="false">														')
document.write('	                    <span class="sr-only">Toggle navigation</span>														')
document.write('	                    <span class="icon-bar"></span>														')
document.write('	                    <span class="icon-bar"></span>														')
document.write('	                    <span class="icon-bar"></span>														')
document.write('	                </button>														')
document.write('	               <a class="navbar-brand" href="#"> JUNU'S BLOG </a>														')
document.write('	            </div>														')
document.write('	            <div class="collapse navbar-collapse" id="top-ul">														')
document.write('	                <ul class="nav navbar-nav ">														')
document.write('	                    <li class="active"><a href="#"><img src="images/home.png" class="icon" >首页 <span class="sr-only">(current)</span></a></li>														')
document.write('	                    <li><a href="#"><img src="images/share.png" class="icon" > 技术分享</a></li>														')
document.write('	                    <li><a href="#"><img src="images/time.png" class="icon" > Achive</a></li>														')
document.write('	                    <!-- <li><a href="#"><img src="images/life.png" class="icon" > 程序人生</a></li> -->														')
document.write('	                    <li><a href="#"><img src="images/about.png" class="icon" > 关于博主</a></li>														')
document.write('	                </ul>														')
document.write('	            </div><!-- /.navbar-collapse -->														')
document.write('	        </div><!-- /.container-fluid -->														')
