document.write('	<nav class="navbar navbar-inverse navbar-static-top">																')
document.write('	        <div class="container">																')
document.write('	            <div class="navbar-header">																')
document.write('	                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-ul" aria-expanded="false">																')
document.write('	                    <span class="sr-only">Toggle navigation</span>																')
document.write('	                    <span class="icon-bar"></span>																')
document.write('	                    <span class="icon-bar"></span>																')
document.write('	                    <span class="icon-bar"></span>																')
document.write('	                </button>																')
document.write('					<a class="navbar-brand" href="index.html"> JUNU\'S BLOG </a>												')
document.write('	            </div>																')
document.write('	            <div class="collapse navbar-collapse" id="top-ul">																')
document.write('	                <ul class="nav navbar-nav ">																')
document.write('	                    <li class="active"><a href="index.html"><i class="fa fa-rocket" aria-hidden="true"></i>首页 <span class="sr-only">(current)</span></a></li>																')
document.write('	                    <li class="dropdown">																')
document.write('	                            <a href="#" class="dropdown-toggle fa fa-share" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">程序分享 <span class="caret"></span></a>																')
document.write('	                            <ul class="dropdown-menu">																')
document.write('	                                <li><a href="#">三只松鼠</a></li>																')
document.write('	                                <li><a href="#">两只兔子</a></li>																')
document.write('	                                <li><a href="#">一只老鼠</a></li>																')
document.write('	                                <li role="separator" class="divider"></li>																')
document.write('	                                <li><a href="#">欢乐炸金花</a></li>																')
document.write('	                                <li role="separator" class="divider"></li>																')
document.write('	                                <li><a href="chess.html">五子棋</a></li>																')
document.write('	                                <li role="separator" class="divider"></li>																')
document.write('	                                <li><a href="qinghua.html">土味情话</a></li>																')
document.write('	                            </ul>																')
document.write('	                    </li>																')
document.write('						<li><a href="#"><i class="fa fa-archive" aria-hidden="true"></i> Achive</a></li>											')
document.write('						<li><a href="#"><i class="fa fa-times" aria-hidden="true"></i> 程序人生</a></li>											')
document.write('	                    <li><a href="about.html"><i class="fa fa-superpowers" aria-hidden="true"></i> 关于博主</a></li>																')
document.write('	                </ul>																')
document.write('	            </div><!-- /.navbar-collapse -->																')
document.write('	        </div><!-- /.container-fluid -->																')
document.write('	    </nav>																')
