document.write('	<div class="passage">			')
document.write('		<small class="fa fa-clock-o">&nbsp;发布于2020-12-26</small>		')
document.write('		<h3 class="passage-vice"><a href="#">自制的博客静态页面</a></h3>		')
document.write('		<small><i class="fa fa-fire passage-vice" aria-hidden="true"></i>热度99304</small>		')
document.write('		<small><i class="fa fa-font passage-vice" aria-hidden="true"></i>字数≈603字</small>		')
document.write('		<small><i class="fa fa-folder-open passage-vice" aria-hidden="true"></i><a href="#">html/CSS3</a></small>		')
document.write('		<small><i class="fa fa-book passage-vice" aria-hidden="true"></i>阅读时长≈2分钟</small>		')
document.write('		<h4 style=><small>&nbsp;&nbsp;&nbsp;&nbsp;基于Bootstrap,Jquery,CSS3搭建</small></h4>		')
document.write('		<button type="button" class="btn btn-primary fa fa-coffee ">&nbsp;阅读全文</button>		')
document.write('		<div class="passage-buttom">		')
document.write('			<button type="button" class="btn btn-warning fa fa-tags ">&nbsp;Bootstrap</button>	')
document.write('			<button type="button" class="btn btn-warning fa fa-tags ">&nbsp;jquery</button>	')
document.write('			<button type="button" class="btn btn-warning fa fa-tags ">&nbsp;CSS3</button>	')
document.write('		</div>		')
document.write('	</div>			')
