document.write('	<div class="personArea">																')
document.write('							<div class="avater">										')
document.write('								<div><img src="images/nickName1.jpg" class="img-responsive center-block img-circle" ></div>									')
document.write('								<H3 align="center">JUNU</H3>									')
document.write('								<div style="text-align: center;font-family: 宋体	;"> <p>时间白驹过隙，转瞬即逝。可这种心情很长，如高山大川，连绵不绝。</p></div>								')
document.write('							</div>										')
document.write('							<div class="social">										')
document.write('																	')
document.write('								<a href="https://github.com/JunYuCoding" target="_blank" class="fa fa-github social-icon"  aria-hidden="true">									')
document.write('								<a href="mailto:1060737917@qq.com" target="_blank" class="fa fa-envelope social-icon" aria-hidden="true"></a>									')
document.write('								<a href="https://blog.csdn.net/qq_45505100/" target="_blank" class="fa  social-icon" aria-hidden="true">C</a>									')
document.write('								<a href="http://wpa.qq.com/msgrd?v=3&uin=1060737917&site=qq&menu=yes  " target="_blank" class="fa fa-qq social-icon" aria-hidden="true" ></a>									')
document.write('								<a href="https://music.163.com/" target="_blank" class="fa fa-music social-icon" aria-hidden="true"></a>									')
document.write('																	')
document.write('							</div>										')
document.write('						</div>											')
document.write('					<div id="app">											')
document.write('						<div class="labelArea"  >											')
document.write('							<p class="" ><b>今日一笑 </b></p>										')
document.write('							<p style="font-size: 16px;">{{joke}} </p>										')
document.write('						</div>											')
document.write('						<div class="labelArea"  >											')
document.write('							<p class="" ><b>每日诗词 </b></p>										')
document.write('							<p style="font-size: 16px;">{{poetry}} </p>										')
document.write('						</div>											')
document.write('					</div>											')
document.write('						<form class="navbar-form navbar-left">											')
document.write('							 <div class="form-group">										')
document.write('								 <input type="text" class="form-control " placeholder="搜点什么呢">									')
document.write('							 </div>										')
document.write('							 <!-- <button class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button> -->										')
document.write('							 <button type="submit" class="btn btn-primary">站内搜索</button>										')
document.write('						 </form>											')
document.write('						 <div class="labelArea ">											')
document.write('								<p class=""><b>文章分类 </b></p>									')
document.write('									<div id="sheet1" class="mui-popover mui-popover-bottom mui-popover-action ">								')
document.write('										<ul class="">							')
document.write('											  <li class="">						')
document.write('												<a href="#" >html </a><span class="badge">4</span>					')
document.write('											  </li>						')
document.write('											  <li class="">						')
document.write('												<a href="#">css </a><span class="badge">2</span>					')
document.write('											  </li>						')
document.write('											  <li class="">						')
document.write('												<a href="#">js </a><span class="badge">9</span>					')
document.write('											  </li>						')
document.write('											  <li class="">						')
document.write('												<a href="#">jquery </a><span class="badge">11</span>					')
document.write('											  </li>						')
document.write('										</ul>							')
document.write('										<!-- 取消 -->							')
document.write('										<!-- <ul class="">							')
document.write('											  <li class="">						')
document.write('												<a href="#sheet1"><b>取消</b></a>					')
document.write('											  </li>						')
document.write('										</ul> -->							')
document.write('									</div>								')
document.write('						 </div>											')
document.write('						 <div class="labelArea">											')
document.write('							<p class=""><b>更多专栏 </b></p>										')
document.write('							<p style="font-size: 16px;">敬请期待！</p>										')
document.write('						 </div>											')
